### ISSUE TITLE
Licensing details and instructions

### ISSUE THREAD

**Issue by ebfull** [zcash/logos#2]
This repository lacks licensing information and advice for contributors. (See #1 as well.)

**Comment by jackgavigan** [comment]
As an interim step, I'd added a pointer to the Trademark Policy to the README file.

I think that the simplest approach is to formally assert the Zerocoin Electric Coin Company's copyright over the logos in this repo, and require that anyone who makes any changes/additions to the repo acknowledges the Company's copyright, and/or assigns the copyright of their changes/additions to the Company.
